### PR TITLE
Media devices ssl

### PR DESCRIPTION
**Pull request by easytarget**
Restores Broken `Tool`, `Menu` and `Camera URL` Settings for users affected by recent chrome security-ratchet changes to camera access resulting in inaccessible settings items and (in chrome console):

    Uncaught TypeError: Cannot read property 'enumerateDevices' of undefined
    at VideoCapture.getDevices (video-capture.js:194) 

It now checks if the device list can be enumerated before attempting to do so, and only displays device selector + omr control if available. Otherwise it displays a 'Device List Unavalable' message + hint. 

See: https://forum.makerforums.info/t/tools-and-macro-menus-not-responsive-after-fresh-install-of-laserweb4/77783

The initial commit of this is a 'vanilla' fix that fixes the problem as minimally as possible.
The full PR takes care of giving the user some meaningful feedback instead of simply displaying an empty selector dialogue.

Screenshot from 2020-08-16 18-08-23

PS: There is probably a ver 'React friendly' way to do this, but I chose to shortcut that with element ID's and setting style tags. So I consider this sort of incomplete but I dont have time/space to learn react.js ;-)

### CODE REVIEW

**Comment by easytarget** [comment]
Not sure what is happening in travis, I'll try to reproduce and fix, this is all a learning excercise for me so any assistance, especially good hints that let me learn and find the solution myself, would be appreciated ;-)

**Comment by easytarget** [comment]
Related: Author has started a re-write and moved to a new branch to do this. Making it the default.
https://github.com/neogeek/gamepad.js/commits/
I'm guessing this means we need to specify the master branch or a specific commit in package.json

**Comment by cprezzi** [comment]
Should I merge this PR or do you want to wait until you found the travis problem?

**Comment by easytarget** [comment]
I see you merged #609, that fixes the travis problem, so there is no reason not to merge this too ;-)

**Comment by easytarget** [comment]
As the travis owner you should be able to trigger a new build if you wish.

**Comment by easytarget** [comment]
Ooh! look at that. I upstreamed my fork, rebased the branch and as if by magic It got rebuilt.

**Pull request merged**
