### PR TITLE
Fresh New UI

### PR DESCRIPTION
**Pull request by marcodallago**
Hello everybody! My compliments for the project. It is very complete, and the setup is very easy!
Unfortunately, since I think internet lacks from Laser Engraving software control of high quality and accessible to everyone, I'd suggest a fresh new UI. I believe this software has all the potential to become the best one, but lacks on intuitive UI and fresh design. I was thinking about redoing the UI but the way you implemented yours is tricky. Not just an html that recalls classes.
Btw, what are your plans? Please consider it, it is just a great tool, it needs to stand out!

### CODE REVIEW

**Comment by openhardwarecoza** [comment]
Post some screenshots of changes and exact details for discussion

**Comment by tbfleming** [comment]
Don't touch the dist/ folder; code generators produce it.

**Comment by jorgerobles** [comment]
@marcodallago Thanks for the compliment!. Please join us and develop! Post some pictures of what's your ideal UI, and will try to get the best of it! 
If you want to contribute LW is based on React Framework.

**Comment by tbfleming** [comment]
@marcodallago please create a new issue, with screenshots, for discussing your proposal. The dist/ folder isn't the source code; even glancing at it can throw your understanding of the underlying architecture way off.

**Comment by tbfleming** [comment]
@marcodallago I just realized you didn't actually touch dist/ or any other files; you created a pull request from gh-pages to dev-es6, which makes it look like you made massive changes to dist/. Pull requests in GitHub aren't for proposals for future changes; they're for pulling in changes you already made. Issues are the best spot for proposing changes.

Since you haven't made changes, you probably don't have any screenshots. Instead, it'd be nice if you create screen mockups of what you propose. Construct them however you want: HTML mockups, MS paint, hand drawn and scanned, whichever is the easiest way to express your ideas.

**Comment by marcodallago** [comment]
Sorry guys for the mess! I'll make some design proposal. In the meantime will you consider Material UI and its components for React? http://www.material-ui.com/

**Comment by jorgerobles** [comment]
Yes, I did take a look for materialize sometime a month or so. It's right, We have to check its ready for small screens too.

**Comment by tbfleming** [comment]
Is there an advantage to material? Something I don't like about Bootstrap (what we have now): it wastes a ton of space, which is why we went with custom CSS for most of the CAM tab.

**Comment by jorgerobles** [comment]
@tbfleming Material, as Bootstrap, show the advantages of a framework, and some nifty JS components already done. But maybe we can go to hardcore CSS. I did not see how difficult is to modify Material to our needs. Bootstrap is hell.

**Comment by marcodallago** [comment]
Yes! It should be responsive ready.
Actually material makes it all nicer, in my opinion. From already implemented animations between elements, to responsive built-in UI.
Guys of smart-dyis made a DriveBoard mod using Material framework: http://www.smartdiys.cc/blog/software-updated/

But in this case, in my vision I see too much stuff in just one screen, and part of it is useless. Maybe some dropdown menu and an UI that helps to focus in the front page to the workflow process could help. All the laser settings should be put in the first launch, with a step by step guide for me (maybe chance to flash inside the app the board?). What do you think?

@tbfleming what needs you encountered?

**Comment by tbfleming** [comment]
So far responsiveness has been a non-priority; I'm unwilling to sacrifice functionality or convenience on normal screens for the sake of smaller ones. We plan to have a separate small screen UI which focuses only on machine control; no document handling or gcode generation.

I'm very hesitant to split up screens, especially the CAM tab. The CAM tab has a top-of-tab to bottom-of-tab flow that's designed to create a flexible relationship between document objects and operations. We did hit an issue where we had to eat up a lot of space which direct new users doing simple tasks (e.g. Create Single, Create Multiple, verbose text on drag targets). There's also a lot of wasted border space that I was opposed to but others thought was necessary.

**Comment by tbfleming** [comment]
Flashing boards from within LW: this would create a support nightmare for us. We want users to get their hardware and firmware set up properly before they use LW. We're fed up with the flood of "my laser won't fire" questions from people who didn't follow firmware setup guides.

**Pull request closed without merging**
