### PR TITLE
Reconciled with dev-es6

### PR DESCRIPTION
**Pull request by raabrp**
My apologies if the routing through Darkly's fork isn't kosher; I was able to incorporate changes from `dev-es6` and get the `barrelDistort` and `image` mapping working.

`reducers/settings.js` currently requires the 'value' (hash?) of the desired camera to be entered as `toolVideoDevice` to work. Is this still desired behavior?

In the settings pane, I chose to display the raw webcam feed along with the controls, rather than the distorted feed with the controls.

I think next steps (beyond merging with `dev-es6`) that I'd be interested in pursuing are accounting for translation and angle of the camera relative to the workspace.

Review is welcome.

### CODE REVIEW

**Comment by jorgerobles** [comment]
@raabrp Sorry but maybe this has some confusion. Opening pull request should be done when new code is developed. As far I've seen, you have uncommented parts of the former unfinished implementation.

`Workspace_video` is too far away of current `dev-es6` and hold all the commits history that make it impossible to review.
Maybe you wanted to merge `workspace_video` with your own checkout of `dev-es6`?

If I were you I should do:

1. Checkout Current dev-es6 on Darklylabs repo
2. Branch dev-es6 to say "webgl_camera" or so.
3. Use pieces of workspace_video to rebuild and develop the transforms.
4. Push it. I we could take a look that branch and help you with questions.
5. Do the pull request. Should be clearer.

**Comment by jorgerobles** [comment]
@raabrp about camera hash, was a request of @DarklyLabs to support multiple camera devices. That's the reason the camera is saved, so can try to connect again that stream upon app start.

**Comment by raabrp** [comment]
@jorgerobles Sorry for the confusion. I interpreted the comments on my last (mistaken) PR (260) to mean that the priority for work on the workspace camera integration was to get this branch merged to master (dev-es6?) prior to working on any additional camera transformations.

There's a bit of git gymnastics here which don't mitigate the confusion.

`DarklyLabs:dev-es6-camera` is a fork of `workspace_video`, in which I uncommented a couple sections of code, merged commits from `dev-es6`, then edited a few files to get things functioning again. Thus, this PR incorporates commits from `dev-es6` (addressing the issue of `workspace_video` being too far behind).

Was that not what was desired? Is this not the way to get `workspace_video` closer to eventual incorporation into `dev-es6`? By playing a bit of catch-up with that branch? I'm not a git power-user (as evinced by my previous PR), so feel free to suggest a different workflow.

Are you instead advocating a new branch on Darkly's fork which merely pulls into `dev-es6` the minimum code from `workspace_video` to incorporate a functioning workspace camera and which makes review easier?

Overall, is this branch (`workspace_video`) merely a dead end and only a possible reference for a desired new implementation, or are there still intentions to merge it back to `dev-es6`?

Cheers.

**Comment by jorgerobles** [comment]
@raabrp 

> Are you instead advocating a new branch on Darkly's fork which merely pulls into dev-es6 the minimum code from workspace_video to incorporate a functioning workspace camera and which makes review easier?

Yes

> Overall, is this branch (workspace_video) merely a dead end and only a possible reference for a desired new implementation, or are there still intentions to merge it back to dev-es6?

Yes

**Comment by raabrp** [comment]
Thanks for the clarification.

**Pull request closed without merging**
