### PR TITLE
DXF text support

### PR DESCRIPTION
**Pull request by iceblu3710**
Basic text support working. 

Draws to canvas using the system fonts so no font handling is required. Pixel data is extrapolated from the offscreen canvas and then scaled to fit the workspace canvas. Large text is a resource hog as the font is especially thousands of tiny squares will fill.

TODO: Come up with an algorithm to trace the shape outline into line segments or ultimately curves.

Not supported:
* Text rotation
* Multiple styles in a single MTEXT

### CODE REVIEW

**Comment by iceblu3710** [comment]
I have started working on a convex hull kind of operation to turn the text into paths. Thinking of doing each character at a time so that its a bunch of simple operations instead of a massive screen operation. I also discovered `ctx.measureText(txt).width` so I can allocate only as large of canvas as I need now.

**Comment by iceblu3710** [comment]
Well I have been having a hell of a time getting text to be actually "useful". A few dead ends on using convex hull algorithms and then a working alpha shape algorithm that created just as many triangles as the point cloud.

I did manage to use the text metrics in the canvas to make the existing implementation less of a memory hog. But when you have a large amount of text is REALLY boggs down the whole app so that's why I am not calling it "useful".

**Comment by jorgerobles** [comment]
@iceblu3710 what is the status of this PR? Is enough to be merged or should need further work?

**Comment by iceblu3710** [comment]
I have now tried about seven different methods to get fonts to work without them being a process/memory hog and all of ended in disaster. Not having access to font data is the crux of the issue and even if I pop up a modal and ask the user to select one from their filesystem I am still forced to pull the data off the canvas.

When LW4 is an Electron app will 'fs' and node style modules be supported? This would remove all my issues...

For the time being I need to wipe my muddied repo and apply the last few tweaks for speed vs resolution.

Here is the million peso question: Would you rather have fast text without styling, or slow text with all the font stylings?

**Comment by openhardwarecoza** [comment]
Fast text,  no styling.  Our built in transforms can be used to make any
corrections like size

**Comment by iceblu3710** [comment]
See #159 for a fully working text commit. I squashed everything down so you can cherry pick  35ed5cc

**Comment by iceblu3710** [comment]
See #164 for an easier to merge PR without the cherry-picking. I forgot how to issue clean branches for a PR.

**Pull request closed without merging**
