### PR TITLE
 refactor gCode generation allowing marlin compatibility

### PR DESCRIPTION
**Pull request by Tibus**
Create a GCode generator field for each machine.
Default is for grbl.
In cam-gcode-raster and cam-gcode-laser-cut, each gcode writing will pass inside the generator and will return the appropriate GCode.

No modification in gCode writing with default generator but with the generator "marlin" this will change the way the laser will turn on and movements to be compatible with stock marlin on 3D printer or so.
For tool on/off the "gCodeToolOn" will be insert at each Intensity change and you can use $INTENSITY variable inside gCodeToolOn to get back the intensity.
By exemple, the GRBL gcode :

G0 X10.0 S100

Will become on Marlin, with gCodeToolOn set to "M106 $INTENSITY" :

M106 S100
G0 X10.0

In Raster mode, GRBL gcode
G1 X10.0 Y20.0 S100
X11.0 Y20.0 S30

will become in marlin :
M106 S100
G1 X10.0 Y20.0
M106 S30
G1 X11.0 Y20.0

### CODE REVIEW

**Comment by jorgerobles** [comment]
@cprezzi, @tbfleming any suggestions before squashing?

**Comment by Tibus** [comment]
Milling and Latice did not change, maybe convert it in the future if needed

**Comment by jorgerobles** [comment]
> Milling and Latice did not change, maybe convert it in the future if needed

will put in the commit notes so the release notes have that noted

**Comment by tbfleming** [comment]
Having a common generator brings it a step closer to where I'd like it to be (see GcodeGenerator in src/lib/cam-gcode-lathe.js), but Marlin isn't so different that it needs a separate class. cam-gcode-laser-cut.js handles the same differences using the gcodeLaserIntensity and gcodeLaserIntensitySeparateLine settings. This allows it to work not just with Marlin, but also with LinuxCNC and Mach 3.

Why does this touch js-aruco? Why are the changes so large?

**Comment by Tibus** [comment]
don't know why js-aruco change, I changed nothing in this. maybee a IDE reformat or so? will revert it asap

**Comment by jorgerobles** [comment]
@tbfleming aruco changes are due permissions not really file changes

image

@Tibus try changing the permissions to 755 (chmod). if cannot, well nothing happens really

About the separate classes are fine for me, could be growing changes in the future (well improbable but not impossible), this way is always assured to be handled properly, and allows to clearly modularize the generators

**Comment by Tibus** [comment]
I changed permission back to 755

**Comment by Tibus** [comment]
Here is the tutorial to change the CR10 to laser engraver, the why I made theses changes : 
https://www.instructables.com/id/CR10s-Magnetic-Removable-Laser-Option-FREN/

**Pull request merged**
