### PR TITLE
Dxf loading

### PR DESCRIPTION
**Pull request by iceblu3710**
GitHub didn't like the branch magically moving back a few commits and closed the pull request. Here is the rewound history before text loading borked everything.  

If everything is back to acceptable this would be good to go out for real world testing. I have found all the issues with my files. Code quality and comments are always accepted.

## Document Specific
* DXF must be saved in R12 ASCII format
* Drawing scale of `1:1` only which is `mm`
* ColorByLayer not currently supported (in progress)
* Color by shape works as expected
* Fill is ignored, causes layering conflicts.

## Current Working
* CIRCLE
* ARC
* LWPOLYLINE
* LINE
* POLYLINE
* SOLID
* POINT

## Partial Support
* Shape Fill - The drawing order renders smaller shapes unclickable on the canvas, fill currently disabled.

## Unsupported
* TEXT
* MTEXT
* DIMENSION

### CODE REVIEW

**Comment by tbfleming** [comment]
Looks good.

**Comment by cojarbi** [comment]
Is this live yet?

**Comment by tbfleming** [comment]
Oops. Forgot to do that. It is now.

**Comment by cojarbi** [comment]
@tbfleming can you double check for me its up? i cant load anything

**Comment by iceblu3710** [comment]
I had to do npm install twice to get dxf-parser module to load in. Its in the json with the other modules but seems to be ignored first run.

**Comment by tbfleming** [comment]
I can't get it to work no matter how many times I npm install. @iceblu3710 do you have any dxf-related extensions loaded in Chrome? On my machine action.payload.file.type comes up empty for DXF files.

**Comment by iceblu3710** [comment]
I just did a clean boot and everything works for me. 

```
git clone git@github.com:LaserWeb/LaserWeb4.git
cd LaserWeb4
npm run installdev
npm start
```

**Pull request merged**
