### PR TITLE
Docker image generation, raspberry Pi

### PR DESCRIPTION
**Pull request by ekerin**
Here's my initial implementation for Docker image generation for Raspberry Pi.

Couple thoughts: 
1. This assumes you'll be using the Pi if you're using Docker.  Not necessarily a valid assumption.
2. Designed to handle a non-development instance, but is still using developer build processes, not sure if that's currently the best I can do, but I had problems doing build prd at one point.
3. Documentation updates to reflect this availability is lacking, suggestions on what to update/write up are greatly appreciated.

### CODE REVIEW

**Comment by cprezzi** [comment]
I think it would be easyer to use the lw.comm-server repo for the Pi Docker image (also the Electron build is made from there). The compiled LW4 frontend files are included in the app folder there and I will add a mobile friendly frontend in the future.

**Comment by ekerin** [comment]
Makes sense, I'll reconfigure.

**Comment by cprezzi** [comment]
@jorgerobles I don't think it makes sense to commit this, as @ekerin has moved the docker to the lw.comm-server repo, as I sugested.

**Comment by jorgerobles** [comment]
:(( ok haven't seen that. @erekin should have cancelled the pr

**Comment by cprezzi** [comment]
@jorgerobles You can revert it ;)

**Comment by jorgerobles** [comment]
Yes.. will do

**Pull request merged**
