### PR TITLE
Workspace video

### PR DESCRIPTION
**Pull request by raabrp**
I prefer seeing the changes on github rather than merging locally.

### CODE REVIEW

**Comment by raabrp** [comment]
Oops. Wrong branch.

**Comment by openhardwarecoza** [comment]
Sounds cool.  What ya working on (;

Camera is one of those features we still need to enhance for V4.1.x (; so if you are the man we need let me know

**Comment by raabrp** [comment]
I was helping DarklyLabs get the webcamera displayed to the workspace and corrected for distortion. I attempted binding frameBuffers and textures correctly to do so before alternately composing the shaders, before I realized that the ``workspace_video`` branch achieved the former. I was merging contributions from   that branch to another on the Darkly fork and mistook my entries for the PR.

Curiously, I'm still struggling to get the result working as desired after the merge, but I think I'll figure it out.

While I'm here, is there an established TODO for the branch (``workspace_video``) if I was looking to contribute? Things like correcting for the camera being off-center and such. What is currently preventing a merge back to ``dev-es6`?

**Comment by openhardwarecoza** [comment]
@jorgerobles and @tbfleming ^

Also, i take it you read all the webcam related closed issues on the
LaserWeb/LaserWeb4/issues?

**Comment by jorgerobles** [comment]
Workspace video branch is too way back current branch, that could throw
some conflicts.

I'm away until monday, sorry.

@openhardwarecoza, I think push current state to master will be a good
idea, before further contributions.

Reilly welcome aboard!!
Please don't hesitate to ask anything. I will try to answer these days, but
I'm only on mobile.

**Comment by openhardwarecoza** [comment]
Enjoy the weekend away! Get some proper rest. Phone off, life on!

**Comment by raabrp** [comment]
Thanks for the welcome. I may do some work to try to get ``workspace_video`` up to speed with ``master`` on my personal fork and introduce that as a PR to this ``workspace_video`` on this fork.

**Pull request closed without merging**
