### PR TITLE
Dxf loading

### PR DESCRIPTION
**Pull request by iceblu3710**
Here is the basic structure for my dxf loader. 

Currently it can only understand lines, but they do render and are selectable. The file tree is completely flat and features are listed as `Layer: Feature: ID` which gets the structure across in the meantime.

### CODE REVIEW

**Comment by iceblu3710** [comment]
I will fix up the issues and move my js into a separate reducer. Once I have working code for all the basic objects I will push it into an npm module. For now, it's way easier to develop inside LW4.

Confirmed to work via:
```
git clone git@github.com:iceblu3710/LaserWeb4.git
git checkout dxf-loading
npm run-script installdev
npm install
npm start
```

installdev skips my addition to package.json for some reason but a second npm install catches it.

**Comment by iceblu3710** [comment]
I have been poking around `../reducers/object.js` and understand the get methods but can the others be used to build the relation state array?

If so I would like to use them as pushing layers as they are found will cause duplicates on less structured files.

**Comment by tbfleming** [comment]
The ```forest``` reducer knows how to add top-level objects (the file) and child objects (layers, lines, etc.). The easiest way to use the forest reducer is to use the ```documents``` reducer.

e.g. ```documentsArray = documents(documentsArray, addDocumentChild(parentId, {child attributes}));```

The reducer takes care of default attribute values; you don't need to use ```initialDocument``` if you take this approach.

It also knows how to modify existing attributes: ```documentsArray = documents(documentsArray, setDocumentAttrs({attributes to set}, objectId));```

If you run into a circular dependency problem with the ```documents``` reducer, then you may use ```documentsForest``` instead.

**Comment by iceblu3710** [comment]
@tbfleming Using the forest solved my layer association issues with one caveat.

```javascript
export function addChild(objectType) {
    let type = objectType.toUpperCase() + '_ADD_CHILD';
    return (parentId, attrs) =>
        ({ type, payload: { parentId, attrs: { ...attrs, id: uuid.v4() } } });
};
````

The add methods explicitly overwrite the id even when they were already set. As I need to keep the layer id's in a collection while parsing my document, the association is overwritten. I changed the destructuring to `attrs.id || uuid.v4()` so that it won't overwrite id's anymore. Hopefully this doesn't go against your design intent.

**Comment by tbfleming** [comment]
@iceblu3710 that change is good.

**Comment by iceblu3710** [comment]
bulges

**Comment by openhardwarecoza** [comment]
Beautiful!

**Comment by jorgerobles** [comment]
Bravo!

**Comment by iceblu3710** [comment]
A few minor issues to work out and then I think we can merge as a beta.

1.  When fillColor is set on solid objects the draw order will cover up the items under them. This is a common thing in CorelDraw that is solved by click cycling through the layers. eg, click once for top, twice for object under top. Not sure how to handle that in Canvas.

2. I think that things like document converters and machine support should be modularized so that they can be maintained separately from the LW4 UI. If I were to make lw.dxf-loader an npm module I would need the document forest features to be turned into an npm module as well. That way each module would be testable on its own.

3. If we don't want to go the above route then how should I MVC my code? Possibly just put it into `../lib` and not MVC anything?

4. I need to add a doc layer to give accreditation to the fact this is essentially a rewrite of the Three.JS features. The only Three.JS thing I blatantly reworked is bulge geometry, everything else is my code. Is there any specific doc template I should be following?

Well, I am off to work for the week, don't know if I will get anything done outside of the weekends. Wanted to get to beta during the seasons off time though.

**Comment by tbfleming** [comment]
1. Do dxf files have fill? If not then it'd be easiest make fill = [0, 0, 0, 0] to solve the click problem. We'll tell SVG users to either put small objects on top of large ones, or don't use fill.

2, 3. The SVG parser module handles this by creating an intermediate format that LW4 converts to its internal format. The only thing the SVG parser module knows about our format is that we need paths in [[x,y,   x,y,   ...], ...].

**Comment by iceblu3710** [comment]
1. dxf files can have a fill but the parser currently ignores it. I was planning on updating that but I will just ignore it for now as it gets in the way of usability.

2. The SVG intermediate code is only 85 lines and I'm at 250 without text support. There are some functions that I can break out into helpers (VectToPolar, VectNormilize, CircleToCoords) and the soon to be text components. I plan to write them so that any future file importing code can use them universally. I suggest these go in `../lib/helpers.js` and then my converter can move to `../lib/dxf-converter.js` and the document reducer will stay uncluttered.

**Comment by tbfleming** [comment]
Sounds good

**Comment by iceblu3710** [comment]
I need some advice on async issues.

The font libraries I am using all have async calls. My documentForest requires the data to be handled fed into the forest in each loop. The async calls will always be after the forest has been built and the `status` object is out of scope.

Any idea how I can force wait for promise to return?

**Comment by tbfleming** [comment]
You can't force wait a promise. Images have a similar issue. You need to handle all async actions before dispatching the load action. 

Chrome 55 added async/await, which makes working with async calls easier. Async/await can't go in the reducers; it also has to be before the dispatch.

**Comment by iceblu3710** [comment]
I have access to the `state` in the callback and can update as required with `setDocumentAttrs()` but the canvas drawing functions have already been called by the time the async returns.

Is there a way to notify the app that state has changed and re-draw?

**Comment by tbfleming** [comment]
Reducers must never make async calls; it leads to all kinds of havoc throughout the entire system.

**Comment by iceblu3710** [comment]
Well, back to the drawing board then...

**Comment by openhardwarecoza** [comment]
Around 13 nov
https://github.com/LaserWeb/LaserWeb3/commits/optimization?after=Y3Vyc29yOqmRwPbASdLf5wxiS6iW2AC6UkW2KzY5
@lautr3k extended LaserWeb3 's DXF support with Fonts in the Optimisation
branch (theres a lot of good work in that branch just sitting there since
the optimisation rewrite is not done,  and the changes too major it cant be
merged back to master either)

**Comment by openhardwarecoza** [comment]
Looks like it depended on threejs too
https://github.com/LaserWeb/LaserWeb3/blob/optimization/public/js/lw/dxf.js#L133

**Comment by iceblu3710** [comment]
There was a reason threejs was so popular, it handles pretty much 100% of the point maths.

I was hoping not to modify the dxf-parser but as the document parsing calls are async already I can handle the text2point conversion in there.

I will see if I can find a sync library before going crazy though.

**Comment by iceblu3710** [comment]
Well, I have very crude text importing working. I had to pull the text out of the dxfTree and feed it into the lw.svgp-parser as a sub document, but I preserved the asyc and dispatch system.

While it works it is horrendously incomplete and has magic numbers to make the scaling work. 
* the lw.svg-parser takes the coords and `/ pxPerInch * 25.4` so I need to `* pxPerInch / 25.4` as the dxf is already in mm and I need to cancel out the scaling. 
* The document size is `0 0 0.2 0.2` as that was the only way to bypass the parsers positioning.
* No dynamic font setting, always Ariel currently
* No font dynamics. This would be very difficult...
* No rotation

Here is an example of the formatted MTEXT string (`Words`):
```
{\fComic Sans MS|b1|i0|c0|p0;W\fComic Sans MS|b0|i1|c0|p0;ords}
```
So I don't see supporting MTEXT any time in the future.

## Document Specific
* DXF must be saved in R12 ASCII format
* Drawing scale of `1:1` only which is `mm`
* ColorByLayer not currently supported (in progress)
* Color by shape works as expected
* Fill is ignored, causes layering conflicts.

## Current Working
* CIRCLE
* ARC
* LWPOLYLINE
* LINE
* POLYLINE
* SOLID
* POINT

## Partial Support
* TEXT
    * TEXT or "Simple Note" without rotation, Bottom Left anchored.

## Unsupported
* MTEXT
* DIMENSION

**Comment by tbfleming** [comment]
Has Arial switched from a proprietary to an open source license?

**Comment by iceblu3710** [comment]
Sun of a... I checked the project licence that had the font as MIT and didn't check the font. 

Would Open Sans work with Apache v2?

This is probably going to be the biggest reason not to support dynamic text.

**Comment by tbfleming** [comment]
Apache 2 is compatible with GPL3.

**Comment by tbfleming** [comment]
Note to others who can hit the "Merge pull request" button. Don't do it; we have to handle this with a special GIT procedure or we'll end up accidentally distributing Arial, which isn't a freely-distributable font.

git delete doesn't delete; it only hides files. Once it gets into the main repo, it will be nearly impossible to purge.

**Comment by iceblu3710** [comment]
I can insert a branch point after ´01aa46f´. Would that trim the font commits from the pull request? If so then I can just hard reset and purge those two commits in my local branch.

I think text will need to be removed completely anyways as AutoCad and DraftSight use Ariel as their base font. This means even though I can render processable output the alignment is different.

The only way I can see to get text working right now is to render it using sysyem fonts to canvas and then creating an outline with a findEdges kind of algorithm. That is way past basic functionality though so I say we roll back this feature and get the core tested first.

**Comment by tbfleming** [comment]
@iceblu3710 that will work

**Pull request closed without merging**
